name: Conditional Workflow

on:
  workflow_dispatch:  # run on request (no need for PR)  
  pull_request:
    # branches:
    #   - main
    # types: [labeled]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - id: label-the-PR
      uses: actions/labeler@v5
    # - name: Get PR labels
    #   id: pr-labels
    #   uses: joerick/pr-labels-action@v1.0.8

    - name: log results
      if: github.event_name == 'pull_request'
      run: |
        echo "Inside the action body"
        # echo ${{ github.event_name }}
        echo all lbels ${{ steps.label-the-PR.outputs.all-labels }}

        export TESTS_TARGET=""
        if [[ ${{ contains(steps.label-the-PR.outputs.all-labels, 'geti-object') }} ]]; then
          echo "geti-object" ${{ contains(steps.label-the-PR.outputs.all-labels, 'geti-object')
          export TESTS_TARGET="tests/pre-merge/integration/test_geti.py $TESTS_TARGET"
        fi
        if [[ ${{ contains(steps.label-the-PR.outputs.all-labels, 'Rest-Clients') }} ]]; then
          echo "Rest-Clients" ${{ contains(steps.label-the-PR.outputs.all-labels, 'Rest-Clients')
          export TESTS_TARGET="tests/pre-merge/integration/rest_clients/ $TESTS_TARGET"
        fi
        if [[ ${{ contains(steps.label-the-PR.outputs.all-labels, 'HTTP-Session') }} ]]; then
          echo "HTTP-Session" ${{ contains(steps.label-the-PR.outputs.all-labels, 'HTTP-Session')
          export TESTS_TARGET="tests/pre-merge/integration/http_session/ $TESTS_TARGET"
        fi
        if [[ ${{ contains(steps.label-the-PR.outputs.all-labels, 'Geti-Utils') }} ]]; then
          echo "Geti-Utils" ${{ contains(steps.label-the-PR.outputs.all-labels, 'Geti-Utils')
          export TESTS_TARGET="tests/pre-merge/integration/utils/ $TESTS_TARGET"
        fi
        echo $TESTS_TARGET

        echo steps.label-the-PR.outputs.all-labels
        echo ${{ github.event.pull_request.labels }}

