name: Conditional Workflow

on:
  workflow_dispatch:  # run on request (no need for PR)  
  pull_request:
    # branches:
    #   - main
    # types: [labeled]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # - id: label-the-PR
    #   uses: actions/labeler@v5
    # - name: Get PR labels
    #   id: pr-labels
    #   uses: joerick/pr-labels-action@v1.0.8

    - name: log results
      run: |
        echo "Inside the action body"
        echo ${{ github.event_name }}
        
        echo steps.label-the-PR.outputs.all-labels
        echo ${{ github.event.pull_request.labels }}
        
        for label in ${{ toJSON(github.event.pull_request.labels.*.name) }}; do
          echo "Processing $label"
        done
