name: Conditional Workflow

on:
  workflow_dispatch:  # run on request (no need for PR)  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - id: label-the-PR
      uses: actions/labeler@v5
      
    - name: log results
      run: |
        echo "Inside the action body"
        echo steps.label-the-PR.outputs.all-labels
        echo ${{ steps.label-the-PR.outputs.all-labels }}
