name: Conditional Workflow

on:
  workflow_dispatch:  # run on request (no need for PR)  
  pull_request:
    # branches:
    #   - main
    # types: [labeled]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - id: label-the-PR
      uses: actions/labeler@v5
    # - name: Get PR labels
    #   id: pr-labels
    #   uses: joerick/pr-labels-action@v1.0.8

    - name: log results
      if: github.event_name == 'pull_request'
      run: |
        echo "Inside the action body"
        # echo ${{ github.event_name }}
        # echo ${{ contains(steps.label-the-PR.outputs.all-labels, 'geti-object') }}

                
        export TESTS_TARGET=""
        declare -A labels_to_tests=(
          ["geti-object"]="tests/pre-merge/integration/test_geti.py"
          ["Rest-Clients"]="tests/pre-merge/integration/rest_clients/"
          ["HTTP-Session"]="tests/pre-merge/integration/http_session/"
          ["Geti-Utils"]="tests/pre-merge/integration/utils/"
        )

        for label in "${!labels_to_tests[@]}"; do
          echo "LABEL=label" >> "$GITHUB_ENV"
          echo "label var" $label
          echo "gh var" ${{ env.LABEL }}
          if [[ ${{ contains(steps.label-the-PR.outputs.all-labels, env.LABEL) }} ]]; then
            export TESTS_TARGET="${labels_to_tests[$label]} "$TESTS_TARGET
          fi
        done
        echo $TESTS_TARGET

        echo steps.label-the-PR.outputs.all-labels
        echo ${{ github.event.pull_request.labels }}

