name: Dockerized workflow
on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
    test_job:
        runs-on: [self-hosted, sdk-runner]
        container:
            image: python:3.10-slim
        steps:
            - uses: actions/checkout@v4
